device: 'cuda'
input_means: [0.406, 0.456, 0.485]
input_stds: [0.225, 0.224, 0.229]
model_backbone: 'Res-50'
model_upsample_channel_num: 256
model_stage_num: 1
output_chl_num: 17
output_shape: [64, 48]
loss_ohkm: True
topk: 8
ctf: True
model_file: 'D:/anaconda3/envs/ak/gait/udp/UDP-RSN18_256x192.pth'
if_flip: True
flip_pairs: [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12],[13, 14], [15, 16]]
upper_body_ids: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
lower_body_ids: [11, 12, 13, 14, 15, 16]
load_min_num: 1
pixel_std: 200
color_rgb: False
test_x_extention: 1.09
test_y_extention: 1.135
w_h_ratio: 0.75
input_shape: [256,192]